### PR TITLE
Restore purchase will now respond with a list of purchases on iOS 

### PR DESCRIPTION
**Pull request by ened**
.. similar to "inventory" call on Android.

This PR is still WIP as my current project is pending review by Apple and I can not test fully.
Will update once done.

Happy to receive comments & suggestions, please.

### CODE REVIEW

**Comment by JackAppDev** [comment]
I suggest also enabling the inventory function for iOS if it isn't already

**Comment by ened** [comment]
Inventory on iOS does not work from my experience. Have to go through "restore purchase" flow in order to re-activate.

**Comment by ened** [comment]
This has now been updated. I'm running a few final tests, then the PR is ready to go.

**Comment by ened** [comment]
Should be ready now, I tested end to end. 

Will consider a separate PR for cosmetics.

**Pull request merged**
